### ISSUE TITLE
automate install pre-requisites

### ISSUE THREAD

**Issue by elliottash** [relatio-nlp/relatio#18]
spacy sm model:

`!python -m spacy download en_core_web_sm`

nltk averaged perceptron tagger

`import nltk`
`nltk.download('averaged_perceptron_tagger')`

**Comment by aplamada** [comment]
This is part of the instructions - please see https://github.com/elliottash/narrative-nlp#installation .
Would you like to have them all downloaded by default?!

**Comment by aplamada** [comment]
Partially done in #43 (for the embeddings part).

**Comment by PinchOfData** [comment]
The current implementation downloads a spacy model if is not downloaded yet, so the user doesn't have to do anything and can specify any spacy model (see https://github.com/relatio-nlp/relatio/blob/relatio-v0.3/relatio/preprocessing.py lines 52-53 and https://github.com/relatio-nlp/relatio/blob/relatio-v0.3/relatio/embeddings.py lines 188-197).

I users want to rely on another library (e.g., gensim, tensorflow, or sentence-transformers), we throw an informative error message telling them to install the package (see https://github.com/relatio-nlp/relatio/blob/relatio-v0.3/relatio/embeddings.py).

In the future, we could make two installs (a lightweight version and a heavyweight version).

**Comment by PinchOfData** [comment]
Done in relatio v0.3
