### ISSUE TITLE
to_dict()

### ISSUE THREAD

**Issue by JonathanElkobi** [relatio-nlp/relatio#21]
While everything works fine in the tutotrial, when I run the model on my own data base I get the error:
TypeError: to_dict() got an unexpected keyword argument 'orient'

So I changed it to  -   docs = dataframe.to_dict('records')
but now I have the error:
TypeError: unsupported type: <class 'str'>

**Comment by PinchOfData** [comment]
Hi Jonathan,
Thanks for raising this. 
Two quick questions:
- which function raises the error?
- would it be possible to provide us with a reproducible example? (perhaps a tiny slice of your data)
Best,

**Comment by JonathanElkobi** [comment]
Greetings,
1.  in split_into_sentences
    docs = dataframe.to_dict(orient='records')
TypeError: to_dict() got an unexpected keyword argument 'orient'
2. I'm working with the [unhri data](https://uhri.ohchr.org/en/our-data-api) which can be found in the link.

**Comment by PinchOfData** [comment]
From the docs:

"""

    A function that splits a list of documents into sentences (using the SpaCy sentence splitter).

    Args:
        dataframe: a pandas dataframe with one column "id" and one column "doc"
        output_path: path to save the output
        progress_bar: print a progress bar (default is False)

    Returns:
        Tuple with the list of document indices and list of sentences

    """

Is your dataframe formatted as a pandas dataframe with an "id" column and a "doc" column?

**Comment by JonathanElkobi** [comment]
Yes

**Comment by PinchOfData** [comment]
Could you show me exactly the first rows of the dataframe and the code you use? It will make it easier for me to help you.

**Comment by JonathanElkobi** [comment]
Thank you for your kind help, I changed the encoding of the data and it works now!

**Comment by PinchOfData** [comment]
That's great. Looking forward to seeing your results. I'm closing the issue.
