### ISSUE TITLE
Does not work well with newer numpy versions?

### ISSUE THREAD

**Issue by psungho** [relatio-nlp/relatio#22]
Seems relatio is based on tensorflow which requires a numpy version downgrade -- however that unfortunately leads to all sorts of bugs/errors  w.r.t. arrays when installed on the base environment. 

Of course you can do everything on a new environment, but wondering if there will be some version or way to make relatio not dependent on tensorflow? (sorry if the question sounds stupid, I'm  an undergrad relatively new to NLP and only started to pick it up a couple months ago due to my growing interest in political economy)

**Comment by aplamada** [comment]
@psungho As you mentioned the way we highly recommend to use relatio is in a separate computational environment. The easiest way is to use either:
- a Python virtual environment using [`venv`](https://docs.python.org/3.8/library/venv.html) or
- a conda environment using [miniconda](https://docs.conda.io/en/latest/miniconda.html) or [Anaconda](https://www.anaconda.com/products/individual-d)

Did you experience issues using the recommended approach?

**Comment by psungho** [comment]
no not at all

**Comment by aplamada** [comment]
Thanks for the update!
One should always use one or more virtual environments per project - this is the desired way (or using containers). 
Unfortunately there is not much that we can do. 

We will see in the future whether we keep the tensorflow dependency or not. 
Can we close the ticket?
