### ISSUE TITLE
Shortcut to filter out SRL mistakes

### ISSUE THREAD

**Issue by elliottash** [relatio-nlp/relatio#32]
SRL sometimes makes mistakes, where non-verbs are identified as the verb, and the resulting annotations are garbage. 

A shortcut to automatically filter these out, would be to run a part of speech tagger on the sentence. When SRL tags non-verbs as the verb, flag that sentence so it can be dropped easily. 

-- in `process_rules` function, add an option to filter for POS tags by semantic role. 
-- by default, only allow for V* (verbs) for the verb semantic role. 
-- could also add a prefab for agents and patients, keeping only adjectives and nouns (but probably not as default).

**Comment by elliottash** [comment]
@Dbhasin1 can make tests for this issue before it's merged into the master branch.

**Comment by PinchOfData** [comment]
Done in relatio v0.3
