### ISSUE TITLE
Method for quickly interpreting clusters

### ISSUE THREAD

**Issue by elliottash** [relatio-nlp/relatio#35]
It would be good to add a method for showing the (e.g.) top 20 words in each embedding cluster.  Right now that has to be done manually.

-- we have Counters in the narrative model class, make it easy to access those and use the .most_common() method.

**Comment by PinchOfData** [comment]
Implemented in the branch relatio-v0.3 (method `self.inspect_cluster()` of the `NarrativeModel()`)
