### ISSUE TITLE
Add options for different spaCy models / different NER taggers

### ISSUE THREAD

**Issue by elliottash** [relatio-nlp/relatio#37]
Right now, the set of spacy models that can be used is limited. That could be made  more flexible. In particular, the package should allow for different NER tagger, eg Stanford NLP’s Stanza library. 

-- currently, allows for different spacy models.

**Comment by PinchOfData** [comment]
Implemented in the branch relatio-v0.3 (method `self.process_roles()` of the `Preprocessor()` class)
