### ISSUE TITLE
Use phrase-BERT for entity encoding

### ISSUE THREAD

**Issue by elliottash** [relatio-nlp/relatio#49]
Add phrase BERT as an option for encoding the entities, before clustering:
https://aclanthology.org/2021.emnlp-main.846.pdf

**Comment by aplamada** [comment]
Should use the implementation mentioned in the paper https://github.com/sf-wa-326/phrase-bert-topic-model ?

**Comment by PinchOfData** [comment]
spaCy has a Roberta implementation: https://spacy.io/models/en (see en_core_web_trf).
[relatio-v0.3](https://github.com/relatio-nlp/relatio/tree/relatio-v0.3) has support for spaCy embeddings, so this could be the easiest approach.
