### ISSUE TITLE
partisan narratives

### ISSUE THREAD

**Issue by paride92** [relatio-nlp/relatio#85]
Could you provide the jupyter notebook to recreate the partisan narratives as shown in the Top 100 Narratives in the U.S. Congressional Record (1994-2015) https://sites.google.com/view/trump-narratives/us-congress?authuser=0#h.d1yv9wolxt6g?

I am trying to apply a similar analysis to a different context, but I am not able to adapt the original code.

**Comment by PinchOfData** [comment]
Hi Paride, you can find our replication folder for the _Political Analysis_ paper [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/3BRWKK&faces-redirect=true).
